### ISSUE TITLE
UI not showing

### ISSUE THREAD

**Issue by Daniel-Haug** [szhu/time-to-bereal-chrome#1]
Hey, I installed the BeNotified extension and I've turned it on and pinned it on chrome, but when I click it, only this small white box appears. Am I doing something wrong? How can this be fixed?
Here's a screensot:
![Unbenannt](https://github.com/szhu/BeNotified/assets/74975314/6474515a-806f-45ee-927d-499a34ee6990)

Thanks.

**Comment by szhu** [comment]
Hi, thanks trying out this extension, and thanks for your report.

It appears that I omitted an important step in the installation instructions. You'll need to run `yarn install` (or `npm install`) and reload the extension.

This extension depends on React, which is pulled in at `npm install`-time. That's why nothing is showing up without it.

Please let me know if that works. If it does, I'll update the readme later on (and I'll leave this issue open until I do).

**Comment by Daniel-Haug** [comment]
Thanks for responding. I'm not sure about the instructions though, how do I run yarn install or npm install? I can't find files called that in the extension folder?
Sorry, I'm not very experienced in installing chrome extensions.

**Comment by szhu** [comment]
No worries. Those are command-line tools that most JavaScript developers already have installed on their computers, but if you're not a developer it probably isn't worth it to install them just to use the extension.

I'll create a ZIP file release that includes all the necessary files (without running any commands) when I have time. I'll post an update here when it's ready.

**Comment by Daniel-Haug** [comment]
Oh thanks, I appreciate the efforts! I can be patient, so no stress

**Comment by slahrichi** [comment]
Had the same issue. All that was needed was: 
1. Download node-js: https://nodejs.org/en
2. Open a terminal, navigate to the downloaded folder on your local machine, and run `npm install `
3. Reload the notification in Chrome

I then pasted the API key received in email and it worked! It would be 10/10 if we could also change the timezone of the notification @Daniel-Haug. Thank you!!

**Comment by Daniel-Haug** [comment]
Thank you! that worked

**Comment by szhu** [comment]
Thanks @slahrichi stepping in with the quick fix!

**Comment by szhu** [comment]
@Daniel-Haug, I've now uploaded a ready-to-install extension into the releases tab, and will create a new release every time we add new features.

You will no longer have to run `npm install` to use the extension. I've updated the instructions in the repo readme (https://github.com/szhu/BeNotified/commit/f74117b740bbef7f1f202b8fe43f160f358664bf) to reflect this.

Thanks again for filing this issue.

**Comment by Daniel-Haug** [comment]
I really appreciate the work you're putting into this project, thank you!
